mapping = {
    'AF': {'official': [], 'other_languages': []},
    'AX': {'official': ['sv'], 'other_languages': []},
    'AL': {'official': ['sq'], 'other_languages': ['el']},
    'DZ': {'official': ['ar'], 'other_languages': ['fr']},
    'AS': {'official': [], 'other_languages': ['sm', 'en']},
    'AD': {'official': ['ca'], 'other_languages': ['es', 'fr', 'pt']},
    'AO': {'official': ['pt'], 'other_languages': []},
    'AI': {'official': ['en'], 'other_languages': []},
    'AQ': {'official': [], 'other_languages': []},
    'AG': {'official': ['en'], 'other_languages': []},
    'AR': {'official': ['es'], 'other_languages': ['es', 'it', 'de', 'fr']},
    'AM': {'official': ['hy'], 'other_languages': ['ru']},
    'AW': {'official': ['nl'], 'other_languages': ['en', 'es']},
    'AU': {'official': ['en'], 'other_languages': ['zh', 'it']},
    'BS': {'official': ['es'], 'other_languages': []},
    'AZ': {'official': ['az'], 'other_languages': ['ru', 'hy']},
    'BH': {'official': ['ar'], 'other_languages': ['en', 'ur']},
    'BD': {'official': ['bn'], 'other_languages': ['en']},
    'BB': {'official': ['en'], 'other_languages': []},
    'BY': {'official': ['be', 'ru'], 'other_languages': []},
    'BE': {'official': ['nl', 'de', 'fr'], 'other_languages': []},
    'BZ': {'official': ['en'], 'other_languages': ['es']},
    'BJ': {'official': ['fr'], 'other_languages': []},
    'BM': {'official': ['en'], 'other_languages': ['pt']},
    'BT': {'official': ['dz'], 'other_languages': []},
    'BO': {'official': ['es', 'qu', 'ay'], 'other_languages': []},
    'BQ': {'official': [], 'other_languages': []},
    'BA': {'official': [], 'other_languages': []},
    'BW': {'official': ['tn', 'en'], 'other_languages': []},
    'BV': {'official': [], 'other_languages': []},
    'BR': {'official': ['pt'], 'other_languages': ['en', 'es', 'fr']},
    'IO': {'official': [], 'other_languages': []},
    'BN': {'official': ['ms'], 'other_languages': ['en', 'zh']},
    'BG': {'official': ['bg'], 'other_languages': ['tr']},
    'BF': {'official': ['fr'], 'other_languages': []},
    'BI': {'official': ['fr'], 'other_languages': []},
    'KH': {'official': ['km'], 'other_languages': ['en', 'fr']},
    'CM': {'official': ['en', 'fr'], 'other_languages': []},
    'CA': {'official': ['en', 'fr'], 'other_languages': []},
    'CV': {'official': ['pt'], 'other_languages': []},
    'KY': {'official': ['en'], 'other_languages': []},
    'CF': {'official': ['fr'], 'other_languages': []},
    'TD': {'official': ['fr', 'ar'], 'other_languages': []},
    'CL': {'official': ['es'], 'other_languages': []},
    'CN': {'official': ['zh'], 'other_languages': []},
    'CX': {'official': ['en'], 'other_languages': ['zh', 'ms']},
 
}
