mapping = {
    'AF': {'official': [], 'other_languages': []},
    'AX': {'official': ['sv'], 'other_languages': []},
    'AL': {'official': ['sq'], 'other_languages': ['el']},
    'DZ': {'official': ['ar'], 'other_languages': ['fr']},
    'AS': {'official': [], 'other_languages': ['sm', 'en']},
    'AD': {'official': ['ca'], 'other_languages': ['es', 'fr', 'pt']},
    'AO': {'official': ['pt'], 'other_languages': []},
    'AI': {'official': ['en'], 'other_languages': []},
    'AQ': {'official': [], 'other_languages': []},
    'AG': {'official': ['en'], 'other_languages': []},
    'AR': {'official': ['es'], 'other_languages': ['es', 'it', 'de', 'fr']},
    'AM': {'official': ['hy'], 'other_languages': ['ru']},
    'AW': {'official': ['nl'], 'other_languages': ['en', 'es']},
    'AU': {'official': ['en'], 'other_languages': ['zh', 'it']},
    'AT': {'official': ['de'], 'other_languages': ['hr', 'hu']},
    'AZ': {'official': ['az'], 'other_languages': ['ru', 'hy']},
    'BS': {'official': ['es'], 'other_languages': []},
    'BH': {'official': ['ar'], 'other_languages': ['en', 'ur']},
    'BD': {'official': ['bn'], 'other_languages': ['en']},
    'BB': {'official': ['en'], 'other_languages': []},
    'BY': {'official': ['be', 'ru'], 'other_languages': []},
    'BE': {'official': ['nl', 'de', 'fr'], 'other_languages': []},
    'BZ': {'official': ['en'], 'other_languages': ['es']},
    'BJ': {'official': ['fr'], 'other_languages': []},
    'BM': {'official': ['en'], 'other_languages': ['pt']},
    'BT': {'official': ['dz'], 'other_languages': []},
    'BO': {'official': ['es', 'qu', 'ay'], 'other_languages': []},
    'BQ': {'official': [], 'other_languages': []},
    'BA': {'official': [], 'other_languages': []},
    'BW': {'official': ['tn', 'en'], 'other_languages': []},
    'BV': {'official': [], 'other_languages': []},
    'BR': {'official': ['pt'], 'other_languages': ['en', 'es', 'fr']},
    'IO': {'official': [], 'other_languages': []},
    'BN': {'official': ['ms'], 'other_languages': ['en', 'zh']},
    'BG': {'official': ['bg'], 'other_languages': ['tr']},
    'BF': {'official': ['fr'], 'other_languages': []},
    'BI': {'official': ['fr'], 'other_languages': []},
    'KH': {'official': ['km'], 'other_languages': ['en', 'fr']},
    'CM': {'official': ['en', 'fr'], 'other_languages': []},
    'CA': {'official': ['en', 'fr'], 'other_languages': []},
    'CV': {'official': ['pt'], 'other_languages': []},
    'KY': {'official': ['en'], 'other_languages': []},
    'CF': {'official': ['fr'], 'other_languages': []},
    'TD': {'official': ['fr', 'ar'], 'other_languages': []},
    'CL': {'official': ['es'], 'other_languages': []},
    'CN': {'official': ['zh'], 'other_languages': []},
    'CX': {'official': ['en'], 'other_languages': ['zh', 'ms']},
    'CC': {'official': ['ms', 'en'], 'other_languages': []},
    'CO': {'official': ['es'], 'other_languages': []},
    'KM': {'official': ['ar', 'fr'], 'other_languages': []},
    'CG': {'official': ['fr'], 'other_languages': ['ln']},
    'CD': {'official': ['fr'], 'other_languages': ['ln']},
    'CK': {'official': ['en'], 'other_languages': []},
    'CR': {'official': ['es'], 'other_languages': ['en']},
    'CI': {'official': ['fr'], 'other_languages': []},
    'HR': {'official': ['hr'], 'other_languages': ['sr']},
    'CU': {'official': ['es'], 'other_languages': []},
    'CW': {'official': [], 'other_languages': []},
    'CY': {'official': ['el', 'tr'], 'other_languages': ['en']},
    'CZ': {'official': ['cs'], 'other_languages': []},
    'DK': {'official': ['da'], 'other_languages': ['fo', 'de']},
    'DJ': {'official': ['fr', 'ar'], 'other_languages': ['so', 'aa']},
    'DM': {'official': ['en'], 'other_languages': []},
    'DO': {'official': ['es'], 'other_languages': []},
    'EC': {'official': ['es'], 'other_languages': []},
    'EG': {'official': ['ar'], 'other_languages': ['en', 'fr']},
    'SV': {'official': ['es'], 'other_languages': []},
    'GQ': {'official': ['es', 'fr'], 'other_languages': []},
    'ER': {'official': ['ti', 'en', 'ar'], 'other_languages': []},
    'EE': {'official': ['et'], 'other_languages': ['ru']},
    'ET': {'official': ['am'], 'other_languages': ['ti', 'so', 'ar', 'en']},
    'FK': {'official': ['en'], 'other_languages': []},
    'FO': {'official': ['fo', 'da'], 'other_languages': []},
    'FJ': {'official': ['en'], 'other_languages': ['fj']},
    'FI': {'official': ['fi', 'sv'], 'other_languages': []},
    'FR': {'official': ['fr'], 'other_languages': []},
    'GF': {'official': ['fr'], 'other_languages': []},
    'PF': {'official': ['fr'], 'other_languages': []},
    'TF': {'official': [], 'other_languages': []},
    'GA': {'official': ['fr'], 'other_languages': []},
    'GM': {'official': ['en'], 'other_languages': []},
    'GE': {'official': ['ka'], 'other_languages': ['ru', 'hy']},
    'DE': {'official': ['de'], 'other_languages': []},
    'GH': {'official': ['en'], 'other_languages': []},
    'GI': {'official': ['en'], 'other_languages': ['es', 'it', 'pt']},
    'GR': {'official': ['el'], 'other_languages': ['en', 'fr']},
    'GL': {'official': ['da'], 'other_languages': ['kl', 'en']},
    'GD': {'official': ['en'], 'other_languages': []},
    'GP': {'official': ['fr'], 'other_languages': []},
    'GU': {'official': ['en', 'ch'], 'other_languages': []},
    'GT': {'official': ['es'], 'other_languages': []},
    'GG': {'official': ['fr', 'en'], 'other_languages': []},
    'GN': {'official': ['fr'], 'other_languages': []},
    'GW': {'official': ['pt'], 'other_languages': []},
    'GY': {'official': ['en'], 'other_languages': ['hi']},
    'HT': {'official': ['fr', 'ht'], 'other_languages': []},
    'HM': {'official': [], 'other_languages': []},
    'VA': {'official': ['it', 'la', 'fr'], 'other_languages': []},
    'HN': {'official': ['es'], 'other_languages': []},
    'HK': {'official': ['zh', 'en'], 'other_languages': []},
    'HU': {'official': ['hu'], 'other_languages': []},
    'IS': {'official': ['is'], 'other_languages': ['de', 'en']},
    'IN': {'official': ['hi', 'en'], 'other_languages': ['bn', 'ml', 'ta', 'mr', 'te', 'ur', 'gu', 'kn', 'or', 'pa', 'as', 'ks', 'sd', 'sa']},
    'ID': {'official': ['id'], 'other_languages': ['en', 'nl']},
    'IR': {'official': ['fa'], 'other_languages': ['tr', 'ku']},
    'IQ': {'official': ['ar', 'ku'], 'other_languages': ['hy']},
    'IE': {'official': ['ga', 'en'], 'other_languages': []},
    'IM': {'official': [], 'other_languages': []},
    'IL': {'official': ['he'], 'other_languages': ['ar', 'en']},
    'IT': {'official': ['it'], 'other_languages': ['de', 'fr']},
    'JM': {'official': ['en'], 'other_languages': []},
    'JP': {'official': ['ja'], 'other_languages': []},
    'JE': {'official': ['en'], 'other_languages': ['pt']},
    'JO': {'official': ['ar'], 'other_languages': ['en']},
    'KZ': {'official': ['kk', 'ru'], 'other_languages': []},
    'KE': {'official': ['en'], 'other_languages': []},
    'KI': {'official': ['en'], 'other_languages': []},
    'KP': {'official': ['ko'], 'other_languages': ['en']},
    'KR': {'official': ['ko'], 'other_languages': ['en']},
    'KW': {'official': ['ar'], 'other_languages': ['en']},
    'KG': {'official': ['ky', 'ru'], 'other_languages': []},
    'LA': {'official': ['lo'], 'other_languages': ['fr', 'en']},
    'LV': {'official': ['lv'], 'other_languages': ['ru']},
    'LB': {'official': ['ar'], 'other_languages': ['fr', 'en', 'hy']},
    'LS': {'official': ['en'], 'other_languages': ['zu', 'xh']},
    'LR': {'official': ['en'], 'other_languages': []},
    'LY': {'official': ['ar'], 'other_languages': ['en', 'it']},
    'LI': {'official': ['de'], 'other_languages': []},
    'LT': {'official': ['lt'], 'other_languages': ['ru', 'pl']},
    'LU': {'official': ['lb', 'de', 'fr'], 'other_languages': []},
    'MO': {'official': ['pt', 'zh'], 'other_languages': []},
    'MK': {'official': ['mk'], 'other_languages': ['sq', 'tr', 'sr']},
    'MG': {'official': ['mg', 'fr'], 'other_languages': []},
    'MW': {'official': ['ny'], 'other_languages': []},
    'MY': {'official': [], 'other_languages': []},
    'MV': {'official': ['dv'], 'other_languages': ['en']},
    'ML': {'official': ['fr'], 'other_languages': ['bm']},
    'MT': {'official': ['mt', 'en'], 'other_languages': []},
    'MH': {'official': ['mh'], 'other_languages': []},
    'MQ': {'official': ['fr'], 'other_languages': []},
    'MR': {'official': ['ar'], 'other_languages': ['fr', 'wo']},
    'MU': {'official': ['fr'], 'other_languages': []},
    'YT': {'official': ['fr'], 'other_languages': []},
    'MX': {'official': ['es'], 'other_languages': []},
    'FM': {'official': ['en'], 'other_languages': []},
    'MD': {'official': ['mo'], 'other_languages': ['ru']},
    'MC': {'official': ['fr'], 'other_languages': ['en', 'it']},
    'MN': {'official': ['mn'], 'other_languages': ['ru']},
    'ME': {'official': [], 'other_languages': []},
    'MS': {'official': ['en'], 'other_languages': []},
    'MA': {'official': ['ar'], 'other_languages': ['fr']},
    'MZ': {'official': ['pt'], 'other_languages': []},
    'MM': {'official': [], 'other_languages': []},
    'NA': {'official': ['en'], 'other_languages': ['de']},
    'NR': {'official': ['na'], 'other_languages': ['en']},
    'NP': {'official': ['ne'], 'other_languages': []},
    'NL': {'official': ['nl', 'fy'], 'other_languages': []},
    'NC': {'official': ['fr'], 'other_languages': []},
    'NZ': {'official': ['en', 'mi'], 'other_languages': []},
    'NI': {'official': ['es'], 'other_languages': []},
    'NE': {'official': ['fr'], 'other_languages': ['ha']},
    'NG': {'official': ['en'], 'other_languages': ['ha', 'yo', 'ig']},
    'NU': {'official': ['en'], 'other_languages': []},
    'NF': {'official': ['en'], 'other_languages': []},
    'MP': {'official': ['en', 'ch'], 'other_languages': ['zh']},
    'NO': {'official': ['nn', 'nb'], 'other_languages': []},
    'OM': {'official': ['ar'], 'other_languages': ['en', 'ur']},
    'PK': {'official': ['ur', 'en'], 'other_languages': ['pa', 'sd']},
    'PW': {'official': ['en'], 'other_languages': ['ja', 'zh']},
    'PS': {'official': [], 'other_languages': []},
    'PA': {'official': ['es'], 'other_languages': ['en']},
    'PG': {'official': ['en', 'ho'], 'other_languages': []},
    'PY': {'official': ['es', 'gn'], 'other_languages': []},
    'PE': {'official': ['es', 'qu'], 'other_languages': ['ay']},
    'PH': {'official': ['en'], 'other_languages': ['tl']},
    'PN': {'official': ['en'], 'other_languages': []},
    'PL': {'official': ['pl'], 'other_languages': []},
    'PT': {'official': ['pt'], 'other_languages': []},
    'PR': {'official': ['es', 'en'], 'other_languages': []},
    'QA': {'official': ['ar'], 'other_languages': ['en']},
    'RE': {'official': ['fr'], 'other_languages': []},
    'RO': {'official': ['ro'], 'other_languages': ['hu', 'de']},
    'RU': {'official': ['ru'], 'other_languages': []},
    'RW': {'official': ['rw', 'fr', 'en'], 'other_languages': ['sw']},
    'BL': {'official': [], 'other_languages': []},
    'SH': {'official': ['en'], 'other_languages': []},
    'KN': {'official': ['en'], 'other_languages': []},
    'LC': {'official': ['en'], 'other_languages': []},
    'MF': {'official': [], 'other_languages': []},
    'PM': {'official': ['fr'], 'other_languages': []},
    'VC': {'official': ['en', 'fr'], 'other_languages': []},
    'WS': {'official': ['sm', 'en'], 'other_languages': []},
    'SM': {'official': ['it'], 'other_languages': []},
    'ST': {'official': ['pt'], 'other_languages': []},
    'SA': {'official': ['ar'], 'other_languages': []},
    'SN': {'official': ['fr'], 'other_languages': ['wo']},
    'RS': {'official': ['sr'], 'other_languages': ['sq']},
    'SC': {'official': ['en'], 'other_languages': []},
    'SL': {'official': ['en'], 'other_languages': []},
    'SG': {'official': ['en', 'ms'], 'other_languages': ['ta']},
    'SX': {'official': [], 'other_languages': []},
    'SK': {'official': ['sk'], 'other_languages': ['hu', 'uk']},
    'SI': {'official': ['sl'], 'other_languages': []},
    'SB': {'official': ['en'], 'other_languages': []},
    'SO': {'official': ['so'], 'other_languages': ['ar', 'it', 'en']},
    'ZA': {'official': ['en', 'af'], 'other_languages': []},
    'GS': {'official': [], 'other_languages': []},
    'ES': {'official': ['es'], 'other_languages': ['ca', 'gl', 'eu']},
    'LK': {'official': ['si'], 'other_languages': ['ta']},
    'SD': {'official': ['ar'], 'other_languages': ['en']},
    'SR': {'official': ['nl'], 'other_languages': ['en']},
    'SS': {'official': [], 'other_languages': []},
    'SJ': {'official': ['no'], 'other_languages': ['ru']},
    'SZ': {'official': ['en'], 'other_languages': []},
    'SE': {'official': ['sv'], 'other_languages': []},
    'CH': {'official': ['de', 'fr', 'it'], 'other_languages': ['sq', 'pt', 'es', 'en']},
    'SY': {'official': ['ar'], 'other_languages': ['ku', 'hy']},
    'TW': {'official': [], 'other_languages': []},
    'TJ': {'official': ['tg'], 'other_languages': ['ru']},
    'TZ': {'official': ['sw', 'en'], 'other_languages': ['ar']},
    'TH': {'official': ['th'], 'other_languages': ['en']},
    'TL': {'official': [], 'other_languages': []},
    'TG': {'official': ['fr'], 'other_languages': ['ee']},
    'TK': {'official': ['en'], 'other_languages': []},
    'TO': {'official': ['en'], 'other_languages': []},
    'TT': {'official': ['en'], 'other_languages': ['hi', 'fr', 'es', 'zh']},
    'TN': {'official': ['ar', 'fr'], 'other_languages': []},
    'TR': {'official': ['tr'], 'other_languages': ['ku', 'hy', 'ar', 'el']},
    'TM': {'official': ['tk'], 'other_languages': ['ru', 'uz']},
    'TC': {'official': ['en'], 'other_languages': []},
    'TV': {'official': ['en'], 'other_languages': ['sm']},
    'UG': {'official': ['en'], 'other_languages': ['lg', 'sw', 'ar']},
    'UA': {'official': ['uk'], 'other_languages': ['ru', 'pl', 'hu']},
    'AE': {'official': ['ar'], 'other_languages': ['fa', 'en', 'hi', 'ur']},
    'GB': {'official': ['en'], 'other_languages': ['cy', 'gd']},
    'US': {'official': ['en'], 'other_languages': ['es']},
    'UM': {'official': [], 'other_languages': []},
    'UY': {'official': ['es'], 'other_languages': []},
    'UZ': {'official': ['uz'], 'other_languages': ['ru', 'tg']},
    'VU': {'official': ['bi', 'en', 'fr'], 'other_languages': []},
    'VE': {'official': ['es'], 'other_languages': []},
    'VN': {'official': ['vi'], 'other_languages': ['en']},
    'VG': {'official': ['en'], 'other_languages': ['es', 'fr']},
    'VI': {'official': [], 'other_languages': []},
    'WF': {'official': [], 'other_languages': []},
    'EH': {'official': [], 'other_languages': []},
    'YE': {'official': ['ar'], 'other_languages': []},
    'ZM': {'official': ['en'], 'other_languages': ['ny', 'to']},
    'ZW': {'official': ['en'], 'other_languages': ['sn']},
}
